name: PR Check

on: pull_request

jobs:
  pr-check:
    name: PR Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.5
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - run: pnpm p:core check
      - run: pnpm build
      - run: pnpm pg:vanilla-ts rlse:test
