name: PR Check

on: pull_request

jobs:
  pr-check:
    name: PR Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - run: pnpm i --frozen-lockfile

      - run: pnpm p:core lint

      - run: pnpm p:core build

      - run: pnpm pg:vanilla-ts rlse:test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
